### ISSUE TITLE
v0.90 failing due to new release of ember-compatiblity-helpers

### ISSUE THREAD

**Issue by fredjohnd** [machty/ember-concurrency#385]
Hi there,

Not sure if this the correct place to mention this  but my build has been working fine and I haven't changed my package.json in months until I started getting this error when building it:

```
[15:59:22]W:	 [Step 8/10] Cannot read property 'match' of undefined
[15:59:22]W:	 [Step 8/10] TypeError: Cannot read property 'match' of undefined
[15:59:22]W:	 [Step 8/10]     at extractTrueVersion (C:\work\1cea6baf47fa1687\node_modules\ember-compatibility-helpers\utils\extract-true-version.js:11:53)
[15:59:22]W:	 [Step 8/10]     at CoreObject._getComparisonPlugin (C:\work\1cea6baf47fa1687\node_modules\ember-compatibility-helpers\index.js:71:30)
[15:59:22]W:	 [Step 8/10]     at CoreObject.registerTransformWithParent (C:\work\1cea6baf47fa1687\node_modules\ember-compatibility-helpers\index.js:52:35)
```

After looking at the culprit with "npm ls ember-compatibility-helpers"
```
-- ember-concurrency@0.9.0
 `-- ember-compatibility-helpers@1.2.2
   `-- UNMET PEER DEPENDENCY @babel/core@^7.0.0-beta.42
```

While previously I was getting:
```
[15:51:32] :		 [npm install] +-- ember-composable-helpers@1.2.0 
[15:51:32] :		 [npm install] +-- ember-concurrency@0.9.0 
```

Notice the difference of ember-compatibility-helpers version. Before 1.2.0, now 1.2.2.

I think the problem is that ember-concurrency package.json allows using any minor version of ember-compatiblity-helpers which now due to a new release it fails:  https://github.com/machty/ember-concurrency/blob/d887f1c72ce071ed5b9c9b0bd990741d947963ad/package.json#L73

I have tried adding a "resolutions" to my package.json but made no difference.

**Comment by maxfierke** [comment]
hi @fredjohnd, I'd recommend opening an issue on the [ember-compatibility-helpers](https://github.com/pzuraq/ember-compatibility-helpers) repo directly, as if this is the case it's either a bug there or break in semver.

I would also recommend the use of a lock file (via yarn or npm) if you're not already using one, to avoid surprises like this.

**Comment by maxfierke** [comment]
looks like there's a corresponding issue open upstream: https://github.com/pzuraq/ember-compatibility-helpers/issues/47
