### ISSUE TITLE
Not working with ember-cli-babel 8.x

### ISSUE THREAD

**Issue by sebastianhelbig** [machty/ember-concurrency#545]
ember-concurreny: 3.1.1
ember-compatibility-helpers: 1.2.6
ember-cli-babel: 8.1.0

In browser console:

```
loader.js:247 Uncaught (in promise) Error: Could not find module `ember-compatibility-helpers` imported from `ember-concurrency/-private/utils`
    at missingModule (loader.js:247:1)
    at findModule (loader.js:258:1)
    at Module.findDeps (loader.js:168:1)
    at findModule (loader.js:262:1)
    at Module.findDeps (loader.js:168:1)
    at findModule (loader.js:262:1)
    at Module.findDeps (loader.js:168:1)
    at findModule (loader.js:262:1)
    at requireModule (loader.js:24:1)
    at ModuleRegistry.get (index.js:25:1)
```

**Comment by machty** [comment]
I suspect this is already fixed in 4.0.0; please try 4.0.0-beta.1, or just wait a bit longer for the release.

**Comment by machty** [comment]
I'm pretty sure the is fixed in EC4, please reopen if not.
