### ISSUE TITLE
Error When Using in Component Integration Test

### ISSUE THREAD

**Issue by kturney** [machty/ember-concurrency#56]
what I'd expect to work:
```javascript
it('should support paginated ember-concurrency tasks', function() {
    this.set('itemsTask', task(function * (result) {
      return yield Ember.RSVP.resolve(result);
    }));

    page.render(hbs`{{collection-count task=itemsTask}}`);

    expect(page, 'page').to.have.deep.property('count.isVisible', false);

    const items = [ 1, 2, 3, 4 ];
    items.meta = { pagination: { total: 1234, limit: 20, offset: 50 } };
    this.get('itemsTask').perform(items);

    return wait()
      .then(() => {
        expect(page, 'page').to.have.deep.property('count.text', 'Showing 51 - 70 of 1234');

        const items = [ 1, 2, 3, 4 ];
        items.meta = { pagination: { total: 1234, limit: 20, offset: 70 } };
        this.get('itemsTask').perform(items);

        return wait();
      })
      .then(() => {
        expect(page, 'page').to.have.deep.property('count.text', 'Showing 71 - 90 of 1234');
      });
  });
```

the error thrown:
```
Cannot read property '__ember_processes_destroyers__' of undefined
        TypeError: Cannot read property '__ember_processes_destroyers__' of undefined
            at _cleanupOnDestroy (http://localhost:7357/assets/vendor.js:84575:27)
            at init (http://localhost:7357/assets/vendor.js:83744:52)
            at superWrapper [as init] (http://localhost:7357/assets/vendor.js:37626:22)
            at new Class (http://localhost:7357/assets/vendor.js:51358:14)
            at Function.ClassMixinProps.create (http://localhost:7357/assets/vendor.js:51629:14)
            at Object.<anonymous> (http://localhost:7357/assets/vendor.js:83969:19)
            at TaskProperty.ComputedPropertyPrototype.get (http://localhost:7357/assets/vendor.js:29731:28)
            at Object.get (http://localhost:7357/assets/vendor.js:35331:19)
            at Object.exports.default._emberMetalStreamsStream.default.extend.compute (http://localhost:7357
/assets/vendor.js:36428:40)
            at Object.BasicStream.value (http://localhost:7357/assets/vendor.js:36621:27)
```
which seems to trace to https://github.com/machty/ember-concurrency/blob/72f70b6c327f5242ca623d61ea0595b5f9093896/addon/utils.js#L69

what works:
```javascript
it('should support paginated ember-concurrency tasks', function() {
    this.setProperties({
      willDestroy() {},
      itemsTask: task(function * (result) {
        return yield Ember.RSVP.resolve(result);
      })
    });

    page.render(hbs`{{collection-count task=itemsTask}}`);

    expect(page, 'page').to.have.deep.property('count.isVisible', false);

    const items = [ 1, 2, 3, 4 ];
    items.meta = { pagination: { total: 1234, limit: 20, offset: 50 } };
    this.get('itemsTask').perform(items);

    return wait()
      .then(() => {
        expect(page, 'page').to.have.deep.property('count.text', 'Showing 51 - 70 of 1234');

        const items = [ 1, 2, 3, 4 ];
        items.meta = { pagination: { total: 1234, limit: 20, offset: 70 } };
        this.get('itemsTask').perform(items);

        return wait();
      })
      .then(() => {
        expect(page, 'page').to.have.deep.property('count.text', 'Showing 71 - 90 of 1234');
      });
  });
```
notice the addition of a fake `willDestroy` method on line 3.

I'm guessing the Ember integration test context doesn't have a willDestroy method, which is why the fake is needed. Is there a way ember-concurrency can detect that and not hang `__ember_processes_destroyers__` off of it?

**Comment by BryanCrotaz** [comment]
See PR #66
